version: "3.8"

services:
  postgres:
    container_name: pizzashop-api
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pizzashop
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    restart: unless-stopped
    networks:
      - pizzashop_ntwk
    user: 1000:1000
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ezample@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - pizzashop_ntwk

networks: 
  pizzashop_ntwk:
     driver: bridge  
