version: '3.8'

services:
  postgres:
    container-name: pizzashop-api
    image: postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER: docker
      - POSTGRES_PASSWORD: docker
      - POSTGRES_DB: pizzashop
      - PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
